# Docker compose file for lvlie docker images. We use the automatically built docker images from the hub, so we dont specify the build key.
# The source however is in the same git repository.

version: '2'

services:
  sabnzbd:
    container_name: sabnzbd
    hostname: sabnzbd
    image: docker.io/linuxserver/sabnzbd:latest
    ports:
     - "8088:8080"
    volumes:
     - /mnt/synology_nfs/_prog/sabnzbd/:/config/
     - /mnt/synology_nfs/_cache/:/cache/
     - /mnt/synology_nfs/:/data/
    restart: always
    environment:
      - TZ=Europe/Amsterdam
      - PUID=1026
      - PGID=1026
  sickrage:
    container_name: sickrage
    hostname: sickrage
    image: docker.io/linuxserver/sickrage:latest
    ports:
      - "8089:8081"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/synology_nfs/:/config/
      - /mnt/synology_nfs/_tv:/tv/
      - /mnt/synology_nfs/_cache/:/downloads
    restart: always
    environment:
      - TZ=Europe/Amsterdam
      - PUID=1026
      - PGID=1026
  couchpotato:
    container_name: couchpotato
    build: ./couchpotato
    image: docker.io/lvlie/couchpotato
    ports:
      - "5050:5050"
    volumes:
      - /mnt/synology_nfs/_prog/couchpotato/:/config/couchpotato/
      - /mnt/synology_nfs/_movies/:/data/Movies/
      - /mnt/synology_nfs/_cache/:/cache/
    restart: always
  plex:
    container_name: plex
    hostname: plex
    image: docker.io/linuxserver/plex:latest
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/synology_nfs/_prog/plex/:/config/
      - /mnt/synology_nfs/:/data/
    restart: always
    environment:
      - TZ=Europe/Amsterdam
      - PUID=1026
      - PGID=1026
      - VERSION=latest
  unifi:
    container_name: unifi
    image: docker.io/linuxserver/unifi:latest
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8443:8443"
      - "8843:8843"
      - "8880:8880"
      - "3478:3478/udp"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/synology_nfs/_prog/unifi/:/config
    restart: always
    environment:
      - PUID=1026
      - PGID=1026
  hass:
    container_name: hass
    image: docker.io/homeassistant/home-assistant
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/synology_nfs/_prog/homeassistant/:/config/
    restart: always
